// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsckgqCQZWEfkw9mSWEcHRJr-jlgVHmq0',
    appId: '1:631611078050:web:6cc62dd292b6007319aefb',
    messagingSenderId: '631611078050',
    projectId: 'pillyzecopy',
    authDomain: 'pillyzecopy.firebaseapp.com',
    storageBucket: 'pillyzecopy.appspot.com',
    measurementId: 'G-9VWMLEKY6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUUKg4PbO6CcADM2SK-nSDQKyDPTMpqE',
    appId: '1:631611078050:android:2c4ca1c89e1ac31919aefb',
    messagingSenderId: '631611078050',
    projectId: 'pillyzecopy',
    storageBucket: 'pillyzecopy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChGP1MOOvCOgOLUEjJ8am0o-rbEhsRQV0',
    appId: '1:631611078050:ios:01df1ebb8c406e5619aefb',
    messagingSenderId: '631611078050',
    projectId: 'pillyzecopy',
    storageBucket: 'pillyzecopy.appspot.com',
    iosBundleId: 'com.example.pillyzeCopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChGP1MOOvCOgOLUEjJ8am0o-rbEhsRQV0',
    appId: '1:631611078050:ios:3ba9295697309ce919aefb',
    messagingSenderId: '631611078050',
    projectId: 'pillyzecopy',
    storageBucket: 'pillyzecopy.appspot.com',
    iosBundleId: 'com.example.pillyzeCopy.RunnerTests',
  );
}
